export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED';
export const GET_PRODUCTS_SUCESS = 'GET_PRODUCTS_SUCESS';

export const NEW_PRODUCT_REQUESTED = 'NEW_PRODUCT_REQUESTED';
export const NEW_PRODUCT_SUCESS = 'NEW_PRODUCT_SUCESS';
export const NEW_PRODUCT_FAILED = 'NEW_PRODUCT_FAILED';

export const UPDATE_PRODUCT_REQUESTED = 'UPDATE_PRODUCT_REQUESTED';
export const UPDATE_PRODUCT_SUCESS = 'UPDATE_PRODUCT_SUCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT_REQUESTED = 'DELETE_PRODUCT_REQUESTED';
export const DELETE_PRODUCT_SUCESS = 'DELETE_PRODUCT_SUCESS';
